# 应用名称
spring:
  application:
    name: mall-portal-shop
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 5ialan.com:8848
        namespace: public

# 应用服务 WEB 访问端口
server:
  port: 8887

dubbo:
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  cloud:
    subscribed-services: shop-service-provider,user-service-provider
  scan:
    base-packages: com.alan.mall.portal.shop
  consumer:
    timeout: 5000



springdoc:
  swagger-ui:
    enabled: true

user:
  captchaFlag: true
